### ISSUE TITLE
Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.Tmdb.Trailers.Providers.TrailerIntroProvider

### ISSUE THREAD

**Issue by MidnightWolf420** [crobibero/jellyfin-plugin-tmdb-trailers#109]
for awhile I've had this issue no matter what i tried it didn't work even deleting the plugin files didn't fix it

```
[02:56:45] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.Tmdb.Trailers.Providers.TrailerIntroProvider
System.InvalidOperationException: Unable to resolve service for type 'Jellyfin.Plugin.Tmdb.Trailers.TmdbManager' while attempting to activate 'Jellyfin.Plugin.Tmdb.Trailers.Providers.TrailerIntroProvider'.
at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[02:56:45] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.Tmdb.Trailers.Channels.TmdbExtrasChannel
System.InvalidOperationException: Unable to resolve service for type 'Jellyfin.Plugin.Tmdb.Trailers.TmdbManager' while attempting to activate 'Jellyfin.Plugin.Tmdb.Trailers.Channels.TmdbExtrasChannel'.
at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[02:56:45] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.Tmdb.Trailers.Channels.TmdbTrailerChannel
System.InvalidOperationException: Unable to resolve service for type 'Jellyfin.Plugin.Tmdb.Trailers.TmdbManager' while attempting to activate 'Jellyfin.Plugin.Tmdb.Trailers.Channels.TmdbTrailerChannel'.
at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[02:56:45] [INF] [1] Main: Kestrel listening on Any IP4 Address
[02:56:46] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[02:56:46] [INF] [1] Jellyfin.Plugin.PlaybackReporting.TaskCleanDb: TaskCleanDb Loaded
[02:56:46] [INF] [1] Jellyfin.Plugin.PlaybackReporting.TaskRunBackup: TaskRunBackup Loaded
[02:56:46] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.Tmdb.Trailers.Channels.TmdbTrailerChannel
System.InvalidOperationException: Unable to resolve service for type 'Jellyfin.Plugin.Tmdb.Trailers.TmdbManager' while attempting to activate 'Jellyfin.Plugin.Tmdb.Trailers.Channels.TmdbTrailerChannel'.
at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
```

**Comment by crobibero** [comment]
What version of Jellyfin are you using?

**Comment by MidnightWolf420** [comment]
10.8.10

**Comment by MidnightWolf420** [comment]
sorry i forgot to share the version i used

**Comment by MidnightWolf420** [comment]
i found the issue it was JellyfinJAV that was breaking it
