### ISSUE TITLE
Jellyfin TMDB Trailers Plugin set to "Malfunctioned" (All versions for 10.8.13)

### ISSUE THREAD

**Issue by Apocalyptichobo** [crobibero/jellyfin-plugin-tmdb-trailers#115]
Hey there, I had to do a fresh install of Jellyfin recently and tried to get your plugin. It was previously working on the same server now it does not -- it appears to be the only plugin that does not work. Below is the error message I am getting when I restart the server:

```
[2024-05-15 14:45:29.087 -04:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "Jellyfin.Plugin.Tmdb.Trailers.Providers.TrailerIntroProvider"
System.InvalidOperationException: Unable to resolve service for type 'Jellyfin.Plugin.Tmdb.Trailers.TmdbManager' while attempting to activate 'Jellyfin.Plugin.Tmdb.Trailers.Providers.TrailerIntroProvider'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[2024-05-15 14:45:29.140 -04:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "Jellyfin.Plugin.Tmdb.Trailers.Channels.TmdbExtrasChannel"
System.InvalidOperationException: Unable to resolve service for type 'Jellyfin.Plugin.Tmdb.Trailers.TmdbManager' while attempting to activate 'Jellyfin.Plugin.Tmdb.Trailers.Channels.TmdbExtrasChannel'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[2024-05-15 14:45:29.140 -04:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "Jellyfin.Plugin.Tmdb.Trailers.Channels.TmdbTrailerChannel"
System.InvalidOperationException: Unable to resolve service for type 'Jellyfin.Plugin.Tmdb.Trailers.TmdbManager' while attempting to activate 'Jellyfin.Plugin.Tmdb.Trailers.Channels.TmdbTrailerChannel'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
```
   
   I am running Jellyfin on a Debian 12 build, dockerized with CasaOS. Let me know if you need any more information.

**Comment by crobibero** [comment]
Sorry, I only support the latest Jellyfin version. I don't know why it isn't working for you on 10.8..13

**Comment by Apocalyptichobo** [comment]
> Sorry, I only support the latest Jellyfin version. I don't know why it isn't working for you on 10.8..13

Ah dang okay, thank you anyways!
