### ISSUE TITLE
Playback error

### ISSUE THREAD

**Issue by flamin-jellyfish** [crobibero/jellyfin-plugin-tmdb-trailers#133]
[2024-10-26 15:08:14.204 -07:00] [ERR] [57] Jellyfin.Plugin.Tmdb.Trailers.TmdbManager: GetPlaybackUrlAsync
System.InvalidOperationException: Input stream collection is empty.
   at YoutubeExplode.Videos.Streams.VideoStreamInfoExtensions.GetWithHighestVideoQuality(IEnumerable`1 streamInfos) in /_/YoutubeExplode/Videos/Streams/IVideoStreamInfo.cs:line 48
   at Jellyfin.Plugin.Tmdb.Trailers.TmdbManager.GetPlaybackUrlAsync(String site, String key)

**Comment by crobibero** [comment]
Due to Youtube removing the pre-combined video + audio feeds the plugin will need fairly major updates to work to pre-download the video. I don't know when I will get around to making this change.
