### ISSUE TITLE
Most trailers won't load, and those that do are limited to 15 seconds

### ISSUE THREAD

**Issue by Mange** [crobibero/jellyfin-plugin-tmdb-trailers#3]
I'm not sure what to say here. I've installed the plugin via the custom repo and after restarting Jellyfin a lot of trailers show up, but only a handful of them have their thumbnails loaded.

Those that don't get any thumbnails never loads, while those that do will load but have a total runtime of 15 seconds, after which they will promptly freeze.

Is there some way I can fix this, or help determine the cause?

**Comment by crobibero** [comment]
I've published a new version of the plugin, hopefully updating the YouTube library fixes the issue

**Comment by Mange** [comment]
I updated the plugin and restarted Jellyfin. Now the channel doesn't show up at all.

I found this in the logs:

```
[INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly "Jellyfin.Plugin.TMDbBoxSets, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/data/plugins/TMDb Box Sets/Jellyfin.Plugin.TMDbBoxSets.dll"
[INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly "OpenSubtitlesHandler, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/data/plugins/Open Subtitles/OpenSubtitlesHandler.dll"
[INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly "Jellyfin.Plugin.OpenSubtitles, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/data/plugins/Open Subtitles/Jellyfin.Plugin.OpenSubtitles.dll"
[INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly "Jellyfin.Plugin.Reports, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/data/plugins/Reports/Jellyfin.Plugin.Reports.dll"
[INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly "Jellyfin.Plugin.Anime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/data/plugins/Anime/Jellyfin.Plugin.Anime.dll"
[INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly "Jellyfin.Plugin.Bookshelf, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/data/plugins/Bookshelf/Jellyfin.Plugin.Bookshelf.dll"
[INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly "Jellyfin.Plugin.CoverArtArchive, Version=1.0.0.3, Culture=neutral, PublicKeyToken=null" from "/config/data/plugins/Cover Art Archive/Jellyfin.Plugin.CoverArtArchive.dll"
[INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly "Jellyfin.Plugin.KodiSyncQueue, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/data/plugins/Kodi Sync Queue/Jellyfin.Plugin.KodiSyncQueue.dll"
[INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly "LiteDB, Version=4.1.4.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27" from "/config/data/plugins/Kodi Sync Queue/LiteDB.dll"
[INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly "Jellyfin.Plugin.Tmdb.Trailers, Version=4.2020.1122.1627, Culture=neutral, PublicKeyToken=null" from "/config/data/plugins/TMDb Trailers/Jellyfin.Plugin.Tmdb.Trailers.dll"
[INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly "TMDbLib, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null" from "/config/data/plugins/TMDb Trailers/TMDbLib.dll"
[INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly "YouTubeFetcher.Core, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null" from "/config/data/plugins/TMDb Trailers/YouTubeFetcher.Core.dll"
[ERR] [1] Emby.Server.Implementations.ApplicationHost: Error getting exported types from "YouTubeFetcher.Core, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null"
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Http, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

File name: 'Microsoft.Extensions.Http, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()


[INF] [1] Jellyfin.Plugin.KodiSyncQueue.Data.DbRepo: Jellyfin.Plugin.KodiSyncQueue IS NOW STARTING!!!
[INF] [1] Jellyfin.Plugin.KodiSyncQueue.Data.DbRepo: Creating DB Repository...
[ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "Jellyfin.Plugin.Tmdb.Trailers.Channels.TmdbExtrasChannel"
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

File name: 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.get_Signature()
   at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
   at System.Reflection.RuntimeConstructorInfo.GetParameters()
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)


[ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "Jellyfin.Plugin.Tmdb.Trailers.Channels.TmdbTrailerChannel"
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

File name: 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.get_Signature()
   at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
   at System.Reflection.RuntimeConstructorInfo.GetParameters()
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)


[INF] [1] Main: Kestrel listening on all interfaces
[WRN] [1] Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository: Using an in-memory repository. Keys will not be persisted to storage.
[WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
[WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {56f366e8-9952-4ec2-bd7d-9cb9d5cb7227} may be persisted to storage in unencrypted form.
[INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[INF] [1] Jellyfin.Plugin.KodiSyncQueue.ScheduledTasks.FireRetentionTask: Retention Task Scheduled!
[ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "Jellyfin.Plugin.Tmdb.Trailers.Channels.TmdbTrailerChannel"
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

File name: 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.get_Signature()
   at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
   at System.Reflection.RuntimeConstructorInfo.GetParameters()
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
```

Versions:

```
Jellyfin version: "10.6.4"
Environment Variables: ["[JELLYFIN_CONFIG_DIR, /config]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_CACHE_DIR, /config/cache]", "[JELLYFIN_DATA_DIR, /config/data]"]
Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg", "--webdir=/usr/share/jellyfin/web"]
Operating system: "Linux"
Architecture: X64
64-Bit Process: True
User Interactive: True
```

(Running via Docker)

**Comment by crobibero** [comment]
I've updated the plugin for 10.7 with plugin version 5.2021.102.250. I currently get full playback for trailers

**Comment by Mange** [comment]
Great! I'll try again when 10.7 is stable. Thank you for the support! :heart:

**Comment by Mange** [comment]
Now that 10.7 has been released I can confirm that the plugin has started working now.

---

It still stops after 3 seconds, then after around 5 seconds another 3 seconds are added to the playback, and so on. Seems like it's a transcoding issue or something.

**Comment by crobibero** [comment]
I believe al remote streams in this fashion transcode, so you are correct
