### ISSUE TITLE
Trailers are not showing up

### ISSUE THREAD

**Issue by lyz-code** [crobibero/jellyfin-plugin-tmdb-trailers#5]
Hi, I've installed the version 4.2020.1122.1627 on my jellyfin 10.6.4 using linuxserver/jellyfin:latest.

The plugin is installed correctly, I can modify the settings, but when I go to Trailers I receive:

```
Nothing here.

Install the trailers channel to enhance your movie experience by adding a library of internet trailers.
```

Logs show the following error:

```
[10:31:44] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.Tmdb.Trailers.Channels.TmdbTrailerChannel
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

File name: 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.get_Signature()
   at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
   at System.Reflection.RuntimeConstructorInfo.GetParameters()
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
```

Thanks for the plugin

**Comment by crobibero** [comment]
This is fixed for Jellyfin 10.7 and plugin version 5.2021.102.250
