### ISSUE TITLE
Trailers have no name?

### ISSUE THREAD

**Issue by cvium** [crobibero/jellyfin-plugin-tmdb-trailers#6]
Tested with release-10.7.z. Looks like the trailers don't have a name which causes this when refreshing metadata:

```
[22:40:09] [ERR] [34] MediaBrowser.Providers.Manager.ProviderManager: Error refreshing item
System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.Match(String input)
   at Emby.Naming.Video.CleanStringParser.TryClean(String name, Regex expression, ReadOnlySpan`1& newName)
   at Emby.Naming.Video.CleanStringParser.TryClean(String name, IReadOnlyList`1 expressions, ReadOnlySpan`1& newName)
   at Emby.Naming.Video.VideoResolver.TryCleanString(String name, ReadOnlySpan`1& newName)
   at Emby.Server.Implementations.Library.LibraryManager.ParseName(String name) in C:\Users\claus\RiderProjects\jellyfin\Emby.Server.Implementations\Library\LibraryManager.cs:line 2681
   at MediaBrowser.Controller.Entities.Trailer.BeforeMetadataRefresh(Boolean replaceAllMetdata) in C:\Users\claus\RiderProjects\jellyfin\MediaBrowser.Controller\Entities\Trailer.cs:line 66
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken) in C:\Users\claus\RiderProjects\jellyfin\MediaBrowser.Providers
\Manager\MetadataService.cs:line 128
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken) in C:\Users\claus\RiderProjects\jellyfin\MediaBrowser.Controller\Entities\BaseItem.cs:line 1
410
   at MediaBrowser.Providers.Manager.ProviderManager.RefreshItem(BaseItem item, MetadataRefreshOptions options, CancellationToken cancellationToken) in C:\Users\claus\RiderProjects\jellyfin\MediaBrowser.Providers\Manager\Prov
iderManager.cs:line 1109
   at MediaBrowser.Providers.Manager.ProviderManager.StartProcessingRefreshQueue() in C:\Users\claus\RiderProjects\jellyfin\MediaBrowser.Providers\Manager\ProviderManager.cs:line 1088

**Comment by crobibero** [comment]
Fixed in `5.2021.515.1305`
