### ISSUE TITLE
Could not start this plugin

### ISSUE THREAD

**Issue by 6xingyv** [crobibero/jellyfin-plugin-tmdb-trailers#62]
When I try to use this plugin on Jellyfin 10.8.9, it just said ***Malfunctioned***
## Environment
```
- OS: Windows 11 Insider Preview Dev 25295.1000
- Storage: Local
```
## Logs
``` Log
[2023-02-24 18:35:31.419 +08:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "Jellyfin.Plugin.Tmdb.Trailers.Providers.TrailerIntroProvider"
System.InvalidOperationException: Unable to resolve service for type 'Jellyfin.Plugin.Tmdb.Trailers.TmdbManager' while attempting to activate 'Jellyfin.Plugin.Tmdb.Trailers.Providers.TrailerIntroProvider'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[2023-02-24 18:35:31.584 +08:00] [INF] [1] Jellyfin.MeiamSub.Shooter.ShooterProvider: MeiamSub.Shooter Init
[2023-02-24 18:35:31.590 +08:00] [INF] [1] Jellyfin.MeiamSub.Thunder.ThunderProvider: MeiamSub.Thunder Init
[2023-02-24 18:35:31.605 +08:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "Jellyfin.Plugin.Tmdb.Trailers.Channels.TmdbExtrasChannel"
System.InvalidOperationException: Unable to resolve service for type 'Jellyfin.Plugin.Tmdb.Trailers.TmdbManager' while attempting to activate 'Jellyfin.Plugin.Tmdb.Trailers.Channels.TmdbExtrasChannel'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[2023-02-24 18:35:31.623 +08:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "Jellyfin.Plugin.Tmdb.Trailers.Channels.TmdbTrailerChannel"
System.InvalidOperationException: Unable to resolve service for type 'Jellyfin.Plugin.Tmdb.Trailers.TmdbManager' while attempting to activate 'Jellyfin.Plugin.Tmdb.Trailers.Channels.TmdbTrailerChannel'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
```

**Comment by crobibero** [comment]
I have the plugin working fine on 10.8.9 so I'm not sure how I can help.

**Comment by 6xingyv** [comment]
Magically, it works after multiple restart....
