### ISSUE TITLE
Playback Error

### ISSUE THREAD

**Issue by brunoherrera** [crobibero/jellyfin-plugin-tmdb-trailers#73]
Playback Error
This client isn't compatible with the media and the server isn't sending a compatible media format.

idk what the hell this is either I don't have a path like that anywhere "D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Videos\VideoController.cs"

```
[22:51:23] [ERR] [88] Jellyfin.Plugin.Tmdb.Trailers.TmdbManager: GetPlaybackUrlAsync
YoutubeExplode.Exceptions.VideoUnavailableException: Video 'ye63hQLDj4k' is not available.
   at YoutubeExplode.Videos.VideoController.GetPlayerResponseAsync(VideoId videoId, Boolean isEmbedded, CancellationToken cancellationToken) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Videos\VideoController.cs:line 85
   at YoutubeExplode.Videos.VideoController.GetPlayerResponseAsync(VideoId videoId, CancellationToken cancellationToken) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Videos\VideoController.cs:line 94
   at YoutubeExplode.Videos.Streams.StreamClient.GetManifestAsync(VideoId videoId, CancellationToken cancellationToken) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Videos\Streams\StreamClient.cs:line 151
   at Jellyfin.Plugin.Tmdb.Trailers.TmdbManager.GetPlaybackUrlAsync(String site, String key)
```

**Comment by crobibero** [comment]
> Video 'ye63hQLDj4k' is not available.

**Comment by brunoherrera** [comment]
> ye63hQLDj4k

https://www.youtube.com/watch?v=ye63hQLDj4k

**Comment by brunoherrera** [comment]
I wouldn't have wasted my time opening an issue if it was that easy, none of the trailers work even though the video IS available

**Comment by crobibero** [comment]
Please give v11 a try.

**Comment by brunoherrera** [comment]
> Please give v11 a try.

Hi,

TMDb Trailers11.0.0.0
Status: Malfunctioned

and when I click it it says Alert This plugin has no settings to set up.

I'm using [Jellyfin Stable Combined v10.8.10](https://repo.jellyfin.org/releases/server/windows/versions/stable/combined/10.8.10/) on Windows 10

**Comment by crobibero** [comment]
Please post logs

**Comment by brunoherrera** [comment]
> Please post logs

[log_20230509.log](https://github.com/crobibero/jellyfin-plugin-tmdb-trailers/files/11437010/log_20230509.log)

**Comment by crobibero** [comment]
Please try v12

**Comment by brunoherrera** [comment]
> Please try v12

fixed! thanks!!
